apiVersion: app.fybrik.io/v1beta1
kind: FybrikApplication
metadata:
  name: app-finance
  namespace: fybrik-notebook-sample
spec:
  appInfo:
    intent: "read"
  selector:
    workloadSelector:
      matchLabels:
        app: nb-finance
        team: finance
  data:
    - dataSetID: fybrik-notebook-sample/house-price-bd
      requirements:
        interface:
          protocol: fybrik-arrow-flight
          dataformat: csv
