apiVersion: apps/v1
kind: Deployment
metadata:
  name: nb-finance
  namespace: fybrik-notebook-sample
  labels:
    app: nb-finance
    team: finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nb-finance
  template:
    metadata:
      labels:
        app: nb-finance
        team: finance
    spec:
      containers:
        - name: notebook
          image: jupyter/base-notebook:latest
          ports:
            - containerPort: 8888